inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2